import { useCallback, useRef } from 'react';
import { audioKey } from '../utils/audioKey';
import { getAudioUrl } from '../utils/assetUrl';

let audioCtx = null;
function getAudioCtx() {
  if (!audioCtx) audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  // Mobile browsers suspend AudioContext until a user gesture resumes it
  if (audioCtx.state === 'suspended') audioCtx.resume();
  return audioCtx;
}

// Pre-recorded audio index, split per language. Each manifest is
// `{ "<audioKey>": "<hash>" }`, generated by scripts/upload-r2.mjs and tracked
// in git. We use a non-eager glob so Vite code-splits each language's manifest
// into its own chunk — the main bundle stays decoupled from the audio total
// (designed to scale to tens of thousands of files across many languages).
// Filenames/keys are produced with `audioKey(text, lang)`, and looked up here
// with the same function so the two always match.
const MANIFEST_LOADERS = import.meta.glob('../data/audio-manifest/*.json');
const _audioManifests = {}; // lang -> { audioKey: hash }
// In-flight loads, so every caller during the download awaits the SAME import
// instead of firing its own. Without this, the preload effect and each word
// spoken before it resolves each kick off a separate fetch of the same chunk.
const _manifestLoads = {}; // lang -> Promise<{ audioKey: hash }>

// Load (once, cached) the audio manifest for a language. Call from language
// selection / app startup so it's ready before the first word; safe to call
// repeatedly. Returns the manifest map ({} if the language has no manifest).
export function preloadAudioManifest(lang) {
  if (!lang) return Promise.resolve({});
  if (_audioManifests[lang]) return Promise.resolve(_audioManifests[lang]);
  if (_manifestLoads[lang]) return _manifestLoads[lang];
  const loader = MANIFEST_LOADERS[`../data/audio-manifest/${lang}.json`];
  if (!loader) return Promise.resolve((_audioManifests[lang] = {}));
  const load = loader()
    .then((mod) => (_audioManifests[lang] = mod.default || mod))
    // Don't cache the failure: a transient network blip (e.g. flaky wifi when
    // switching language) would otherwise poison this language for the whole
    // session — every word falls back to robotic TTS until the app restarts.
    // Returning {} without caching lets the next word retry the import.
    .catch(() => ({}))
    .finally(() => { delete _manifestLoads[lang]; });
  _manifestLoads[lang] = load;
  return load;
}

// Single persistent <audio> element. iOS Safari only allows playback on a
// media element whose first .play() was triggered by a user gesture — reusing
// one element across word changes (and priming it in primeAudio below) lets
// subsequent .src swaps play without re-locking.
let _recordedAudio = null;
function getRecordedAudio() {
  if (!_recordedAudio) _recordedAudio = new Audio();
  return _recordedAudio;
}

// Deferred-replay slot. On account-switch / OAuth-return / fresh load the
// auto-speak for the first word fires BEFORE any user gesture, so iOS
// blocks it. We stash it here and let an intentional learn-entry gesture
// (check-in OK, guest-mode entry, lang-setup confirm) replay it via
// primeAudio(). Gestures NOT meant to enter learn — tab switches, global
// fallback pointerdown, install-hint — pass `replay: false` so the queued
// word doesn't bleed onto WordList / Settings / Install modals.
let _deferredSpeak = null;

// Set true the first time primeAudio runs the silent-WAV unlock path. The
// shared `_recordedAudio` element only needs that priming once per page
// load; subsequent primeAudio calls must NOT re-run it because doing so
// (`a.pause(); a.currentTime = 0; a.src = silentWav`) would interrupt
// anything currently playing through that element. This matters when two
// primeAudio calls fire from the same gesture — e.g. the global
// pointerdown primer (capture phase) replays a deferred word mp3, then
// handleCheckin's onClick fires primeAudio again and would otherwise stomp
// on the mp3 that just started.
let _primed = false;

// Bumped on every playRecorded call. The shared <audio> element's callbacks
// are async, so a failure for a word the user already swiped past must not
// speak over the word now on screen — only the newest generation may act.
let _playGen = 0;

// Play a recording. `onUnavailable` fires when the file itself won't play
// (network error, 404, decode failure) — NOT when playback was merely blocked
// by the autoplay policy, which is deferred to the next gesture instead.
// Callers pass a TTS fallback so a single failed mp3 leaves the word spoken
// rather than silent.
function playRecorded(url, onUnavailable) {
  const a = getRecordedAudio();
  a.pause();
  a.currentTime = 0;
  const gen = ++_playGen;
  let failed = false;
  const fail = () => {
    // The element's `error` event and the play() rejection both fire for a
    // broken load — report it once, and only for the current word.
    if (failed || gen !== _playGen) return;
    failed = true;
    onUnavailable?.();
  };
  // Overwritten (not accumulated) on every call, so the previous word's
  // handler can't linger on the shared element.
  a.onerror = fail;
  a.src = url;
  const p = a.play();
  if (p && typeof p.catch === 'function') {
    p.catch((err) => {
      if (gen !== _playGen) return;
      // NotAllowedError = the autoplay policy, i.e. audio isn't unlocked yet.
      // Defer and let primeAudio replay it on the next gesture. Browsers that
      // report no name at all get the same benefit-of-the-doubt treatment the
      // original catch-all gave.
      if (!err || !err.name || err.name === 'NotAllowedError') {
        _deferredSpeak = () => playRecorded(url, onUnavailable);
        return;
      }
      // Anything else (network / decode / unsupported source) means the
      // recording is not coming — hand it to the TTS fallback.
      fail();
    });
  }
}

// Call from a user-gesture handler to unlock Web Audio / speechSynthesis /
// the shared <audio> element on iOS Safari. Default `replay: true` also
// drains and plays any queued first-word speak (see _deferredSpeak above);
// pass `replay: false` from gestures that aren't entering learn so the
// queued word doesn't bleed onto other surfaces.
//
// The deferred slot is ALWAYS drained — even on replay:false — so a stale
// word can't sit waiting to play later in the wrong context.
//
// The deferred-replay path and the silent-WAV path are mutually exclusive
// on the shared <audio> element: running both would race (silent WAV's
// async .then resolves after deferred-replay has swapped src and starts
// pausing it).
export function primeAudio({ replay = true } = {}) {
  // primeAudio is only called from user-gesture handlers (global pointerdown
  // primer, tab click, check-in, login, etc.), so getting here means audio
  // is authorized regardless of what `ctx.state` reads on the next tick.
  _audioUnlocked = true;
  try {
    const ctx = getAudioCtx();
    if (ctx.state === 'suspended') ctx.resume();
  } catch {}
  try {
    const u = new SpeechSynthesisUtterance(' ');
    u.volume = 0;
    window.speechSynthesis.speak(u);
    window.speechSynthesis.cancel();
  } catch {}
  // Only drain the deferred slot when this gesture is *meant* to enter
  // learn (handleCheckin / handleLogin / handleLangSetupComplete pass
  // default replay:true). The capture-phase global primer and tab-switch /
  // install-hint gestures pass replay:false and MUST leave the slot intact
  // — otherwise the global primer fires first on the check-in tap and
  // drains the queued first word before handleCheckin's onClick can replay
  // it, and the popup dismiss ends in silence.
  let queued = null;
  if (replay) {
    queued = _deferredSpeak;
    _deferredSpeak = null;
  }
  if (queued) {
    try { queued(); } catch {}
    _primed = true;
  } else if (!_primed) {
    try {
      const a = getRecordedAudio();
      // Drop the last word's error handler before swapping src: a failure
      // reported for the silent WAV must not fire that word's TTS fallback.
      a.onerror = null;
      // Tiny 0-duration silent WAV; just enough to satisfy iOS's "first play
      // from gesture" check and unlock the <audio> element for later plays.
      // Do NOT attach a `.then(() => a.pause())` here: the WAV is empty so it
      // ends instantly on its own, and a deferred pause callback would fire
      // asynchronously — potentially AFTER the next playRecorded swaps src to
      // a real word and calls play(), pausing the word mid-playback. That
      // was the "I tapped 打卡, popup sound played, but the word stayed
      // silent" bug.
      a.src = 'data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA=';
      const p = a.play();
      if (p && typeof p.catch === 'function') p.catch(() => {});
      _primed = true;
    } catch {}
  }
}

let _lastSpeak = { text: '', time: 0 };
// Flipped to true the first time primeAudio runs inside a user gesture.
// AudioContext.resume() is async — its promise resolves on a later tick, so
// `audioCtx.state` can still read 'suspended' for a beat AFTER the gesture
// has already authorized playback. Reading raw `state` causes a false
// "locked" verdict in the check-in flow: handleCheckin unlocks audio →
// setCheckinDay(null) → LearningPage's isVisible flips true → its effect
// calls speakCurrent on the same tick → audioStillLocked() still sees
// 'suspended' → speak gets deferred → no replay happens (the slot would
// only fire on a *future* gesture) → user hears silence.
let _audioUnlocked = false;

function audioStillLocked() {
  if (_audioUnlocked) return false;
  return audioCtx ? audioCtx.state === 'suspended' : true;
}

export function speakWord(text, lang = 'en-US') {
  const now = Date.now();
  if (text === _lastSpeak.text && now - _lastSpeak.time < 600) return;
  _lastSpeak = { text, time: now };
  if (audioStillLocked()) {
    // Defer: replay from primeAudio once a gesture unlocks audio.
    _deferredSpeak = () => {
      window.speechSynthesis.cancel();
      const u = new SpeechSynthesisUtterance(text);
      u.lang = lang;
      u.rate = 0.85;
      u.pitch = lang === 'ja-JP' ? 1.0 : 1.1;
      window.speechSynthesis.speak(u);
    };
    return;
  }
  window.speechSynthesis.cancel();
  const u = new SpeechSynthesisUtterance(text);
  u.lang = lang;
  u.rate = 0.85;
  u.pitch = lang === 'ja-JP' ? 1.0 : 1.1;
  window.speechSynthesis.speak(u);
}

export function speakWordEn(text) {
  speakWord(text, 'en-US');
}

export function speakWordJa(text) {
  speakWord(text, 'ja-JP');
}

export function speakWordZh(text) {
  speakWord(text, 'zh-CN');
}

const TTS_MAP = { en: 'en-US', ja: 'ja-JP', zh: 'zh-CN' };

// Core recorded-audio playback. `ns` is the audio namespace = the manifest name
// AND the public/assets/audio/<ns>/ folder (normally the lang code, but can be a
// dedicated namespace like 'dev-phrases' that must NOT mix into a lang's audio).
// `keyLang` is the language whose audioKey() casing rules name the files (e.g.
// dev phrases are English, so files are lowercased → keyLang 'en'). `ttsLang` is
// the SpeechSynthesis fallback locale when there's no recording.
// How long a word waits for a still-downloading manifest before settling for
// TTS. The manifests are lazy chunks and the dev one is only kicked off once
// the auth session resolves, so on a cold start the first words can arrive
// before the index does. Waiting a beat is what keeps a launch from playing
// robotic TTS for the first few words and the recording for the rest.
const MANIFEST_WAIT_MS = 1500;

// Bumped on every speakFromManifest call, so an async manifest arrival can
// tell whether the word it was resolving for is still the one on screen.
let _manifestSpeakGen = 0;

// Play `text` from an already-loaded manifest, or fall back to TTS when it has
// no recording for it (and when the recording fails to load, see playRecorded).
function playFromManifest(manifest, text, { ns, keyLang, ttsLang }) {
  const key = audioKey(text, keyLang);
  const hash = manifest[key];
  if (hash === undefined) {
    speakWord(text, ttsLang);
    return;
  }
  const url = getAudioUrl(ns, key, hash);
  const now = Date.now();
  if (text === _lastSpeak.text && now - _lastSpeak.time < 600) return;
  _lastSpeak = { text, time: now };
  // The recording exists but won't play (CDN hiccup, offline blip, decode
  // error). Speak it instead of leaving the word silent — clear the dedupe
  // stamp first, or speakWord would swallow the retry as a repeat of the
  // playback we just attempted for this same text.
  const ttsFallback = () => {
    _lastSpeak = { text: '', time: 0 };
    speakWord(text, ttsLang);
  };
  // Audio is still locked (no user gesture yet — e.g. fresh OAuth return
  // mount before the user has tapped anything). Defer the recorded
  // playback so primeAudio can replay it from the next gesture. Without
  // this, playRecorded would call .play() now: on some browsers the
  // returned promise resolves silently instead of rejecting, so the
  // existing .catch-based fallback never sets _deferredSpeak and the
  // first word stays silent forever.
  if (audioStillLocked()) {
    _deferredSpeak = () => playRecorded(url, ttsFallback);
    return;
  }
  window.speechSynthesis.cancel();
  playRecorded(url, ttsFallback);
}

function speakFromManifest(text, opts) {
  const manifest = _audioManifests[opts.ns];
  const gen = ++_manifestSpeakGen;
  if (manifest) {
    playFromManifest(manifest, text, opts);
    return;
  }
  // Manifest still downloading (very first word after launch, or the dev
  // manifest whose preload waits on the auth session). Race the load against a
  // short timer instead of dropping straight to TTS: on a normal connection
  // the index lands in time and the word plays its real recording.
  let settled = false;
  const timer = setTimeout(() => {
    if (settled || gen !== _manifestSpeakGen) return;
    settled = true;
    speakWord(text, opts.ttsLang);
  }, MANIFEST_WAIT_MS);
  preloadAudioManifest(opts.ns).then((loaded) => {
    clearTimeout(timer);
    // `settled` = TTS already spoke this word; a newer generation = the user
    // has moved on. Either way, playing now would talk over what's on screen.
    if (settled || gen !== _manifestSpeakGen) return;
    settled = true;
    playFromManifest(loaded, text, opts);
  });
}

export function speakWordByLang(text, lang) {
  speakFromManifest(text, { ns: lang, keyLang: lang, ttsLang: TTS_MAP[lang] || 'en-US' });
}

// 进阶 (dev) phrases live in their OWN audio namespace — public/assets/audio/
// dev-phrases/ + src/data/audio-manifest/dev-phrases.json — deliberately kept
// out of the shared 'en' audio so the (huge, whitelist-only) dev set never
// bloats the en manifest every English learner loads. The phrases are English,
// so files are named with the en (lowercased) audioKey and TTS falls back to en-US.
export function speakDevPhrase(text) {
  speakFromManifest(text, { ns: 'dev-phrases', keyLang: 'en', ttsLang: 'en-US' });
}

export function playCorrectSound() {
  try {
    const ctx = getAudioCtx();
    const now = ctx.currentTime;
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.connect(gain);
    gain.connect(ctx.destination);
    osc.type = 'sine';
    osc.frequency.setValueAtTime(523.25, now);
    osc.frequency.setValueAtTime(659.25, now + 0.08);
    osc.frequency.setValueAtTime(783.99, now + 0.16);
    gain.gain.setValueAtTime(0.25, now);
    gain.gain.exponentialRampToValueAtTime(0.01, now + 0.35);
    osc.start(now);
    osc.stop(now + 0.35);
  } catch {}
}

export function playWrongSound() {
  try {
    const ctx = getAudioCtx();
    const now = ctx.currentTime;
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.connect(gain);
    gain.connect(ctx.destination);
    osc.type = 'sine';
    osc.frequency.setValueAtTime(330, now);
    osc.frequency.setValueAtTime(260, now + 0.15);
    gain.gain.setValueAtTime(0.2, now);
    gain.gain.exponentialRampToValueAtTime(0.01, now + 0.25);
    osc.start(now);
    osc.stop(now + 0.25);
  } catch {}
}

export function playSlaySound() {
  try {
    const ctx = getAudioCtx();
    const now = ctx.currentTime;

    const osc1 = ctx.createOscillator();
    const gain1 = ctx.createGain();
    osc1.connect(gain1);
    gain1.connect(ctx.destination);
    osc1.type = 'sawtooth';
    osc1.frequency.setValueAtTime(1200, now);
    osc1.frequency.exponentialRampToValueAtTime(200, now + 0.12);
    gain1.gain.setValueAtTime(0.15, now);
    gain1.gain.exponentialRampToValueAtTime(0.01, now + 0.18);
    osc1.start(now);
    osc1.stop(now + 0.2);

    const osc2 = ctx.createOscillator();
    const gain2 = ctx.createGain();
    osc2.connect(gain2);
    gain2.connect(ctx.destination);
    osc2.type = 'square';
    osc2.frequency.setValueAtTime(150, now + 0.05);
    osc2.frequency.exponentialRampToValueAtTime(60, now + 0.15);
    gain2.gain.setValueAtTime(0, now);
    gain2.gain.setValueAtTime(0.2, now + 0.05);
    gain2.gain.exponentialRampToValueAtTime(0.01, now + 0.2);
    osc2.start(now + 0.05);
    osc2.stop(now + 0.25);

    const osc3 = ctx.createOscillator();
    const gain3 = ctx.createGain();
    osc3.connect(gain3);
    gain3.connect(ctx.destination);
    osc3.type = 'sine';
    osc3.frequency.setValueAtTime(2400, now + 0.03);
    osc3.frequency.exponentialRampToValueAtTime(800, now + 0.25);
    gain3.gain.setValueAtTime(0.08, now + 0.03);
    gain3.gain.exponentialRampToValueAtTime(0.01, now + 0.3);
    osc3.start(now + 0.03);
    osc3.stop(now + 0.35);
  } catch {}
}

export function useSpeak() {
  const lastWord = useRef('');
  const speak = useCallback((text) => {
    if (!text) return;
    lastWord.current = text;
    speakWord(text);
  }, []);
  return speak;
}
