// R2 asset URL helper. See memory/project_r2_migration_plan.md.
//
// dev: always local paths under /
// prod with VITE_CDN_BASE set: CDN_BASE + path?v=<hash>
// prod without VITE_CDN_BASE: local fallback (rollback channel)
//
// asset-manifest.json is generated by scripts/upload-r2.mjs (Phase 3).
// Until Phase 3 lands it's an empty {} stub — URLs still work, just
// without ?v=... cache-busting.

import manifest from './asset-manifest.json';

const CDN_BASE = (import.meta.env.VITE_CDN_BASE || '').replace(/\/+$/, '');
const IS_DEV = import.meta.env.DEV;

function encodePath(path) {
  return path
    .split('/')
    .map((seg) => (seg ? encodeURIComponent(seg) : seg))
    .join('/');
}

export function getAssetUrl(path) {
  if (!path) return path;
  if (/^(https?:)?\/\//.test(path)) return path;

  const normalized = path.startsWith('/') ? path : `/${path}`;
  const encoded = encodePath(normalized);

  if (IS_DEV || !CDN_BASE) return encoded;

  const key = normalized.replace(/^\/+/, '');
  const hash = manifest[key];
  const url = CDN_BASE + encoded;
  return hash ? `${url}?v=${hash}` : url;
}

export function getImageUrl(filename) {
  return getAssetUrl(`/images/${filename}`);
}

export function getFigmaAssetUrl(filename) {
  return getAssetUrl(`/assets/figma/${filename}`);
}

export function getInstallAssetUrl(filename) {
  return getAssetUrl(`/assets/install/${filename}`);
}

// Recorded-audio URL. Unlike images, audio hashes are NOT in asset-manifest.json
// — they live in per-language manifests (src/data/audio-manifest/<lang>.json),
// lazy-loaded by useAudio.js — so the hash is passed in by the caller.
// dev / no CDN: local path, no ?v=. prod + CDN: CDN_BASE + path?v=<hash>.
export function getAudioUrl(lang, key, hash) {
  const path = `/assets/audio/${lang}/${key}.mp3`;
  const encoded = encodePath(path);
  if (IS_DEV || !CDN_BASE) return encoded;
  return hash ? `${CDN_BASE + encoded}?v=${hash}` : CDN_BASE + encoded;
}
